"""Add charity relationship to Donation

Revision ID: 68b796ab5cda
Revises: ca9456b31d23
Create Date: 2024-08-24 02:26:59.208061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68b796ab5cda'
down_revision = 'ca9456b31d23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('charity_project_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_donation_charity_project_id_charityproject', 'charityproject', ['charity_project_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_constraint('fk_donation_charity_project_id_charityproject', type_='foreignkey')
        batch_op.drop_column('charity_project_id')

    # ### end Alembic commands ###
